import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import animSet from '../slides';
import Shape from '@/elements/shape';
import { useCallback, useEffect, useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [time, setTime] = useState(0);
  const [top, setTop] = useState(0);

  const scrollListener = useCallback((e: any) => {
    setTop(window.scrollY / window.innerHeight);
  }, [])

  useEffect(() => {
    window.addEventListener('scroll', scrollListener);
    return () => {
      window.removeEventListener('scroll', scrollListener);
    }
  }, [scrollListener]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ width: '100vw', height: '100vh', position: 'fixed', top: 0 }}>
        {
          animSet.slides.map((it,i) => {
            if (it.type === 'shape') {
              return <Shape key={i} 
                            time={top}
                            config={it} />
            }
          })
        }
      </div>
      <main className={styles.main}            
            style={{ width: '100vw', minHeight: `${(Math.ceil(animSet.duration)+1)*100}vh` }}>
      </main>
    </>
  )
}
